import React from 'react';
import { useState } from 'react';
import { Container } from 'react-bootstrap';

const Forpractice = () => {
    const [show, setshow] = useState(true)
    return (
        <div>
            <Container>
                <div className={`${show ? "left_false" : "left_true"} nav_bar`} >
                    <ul className=' list-unstyled mb-0 text-center fs-6 fw-bold text-dark gap-4 pt-5'>
                        <li>Home</li>
                        <li onClick={() => setshow(true)} className='py-4'><a href="#about" className='text-dark'>About</a></li>
                        <li>Services</li>
                        <li className='py-4'>Blog</li>
                        <li>Contact</li>
                        <button onClick={() => setshow(true)} className='btn px-3 py-2 mt-4 btn-info'>click</button>
                    </ul>
                </div>
                <button onClick={() => setshow(false)} className='btn px-3 py-2 mt-4 btn-info'>click</button>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt fugit beatae sapiente perspiciatis repudiandae minus corrupti non dolores, harum illo, eligendi voluptatibus provident id saepe consectetur nisi facilis, numquam labore asperiores incidunt tempora architecto maiores reprehenderit necessitatibus! Dolores reprehenderit inventore saepe iure velit? Blanditiis praesentium dolorum, et cumque consectetur porro exercitationem asperiores hic. Neque sapiente quod odit reiciendis commodi quo, ex impedit aperiam molestiae, eaque, dolores libero. Mollitia dolores dolore eum itaque dignissimos pariatur rerum incidunt, fuga saepe, doloribus, harum fugiat fugit suscipit iusto quo? Provident aliquam assumenda expedita unde amet neque? Neque harum, laborum doloremque sapiente ipsam facere adipisci.</p>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt fugit beatae sapiente perspiciatis repudiandae minus corrupti non dolores, harum illo, eligendi voluptatibus provident id saepe consectetur nisi facilis, numquam labore asperiores incidunt tempora architecto maiores reprehenderit necessitatibus! Dolores reprehenderit inventore saepe iure velit? Blanditiis praesentium dolorum, et cumque consectetur porro exercitationem asperiores hic. Neque sapiente quod odit reiciendis commodi quo, ex impedit aperiam molestiae, eaque, dolores libero. Mollitia dolores dolore eum itaque dignissimos pariatur rerum incidunt, fuga saepe, doloribus, harum fugiat fugit suscipit iusto quo? Provident aliquam assumenda expedita unde amet neque? Neque harum, laborum doloremque sapiente ipsam facere adipisci.</p>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt fugit beatae sapiente perspiciatis repudiandae minus corrupti non dolores, harum illo, eligendi voluptatibus provident id saepe consectetur nisi facilis, numquam labore asperiores incidunt tempora architecto maiores reprehenderit necessitatibus! Dolores reprehenderit inventore saepe iure velit? Blanditiis praesentium dolorum, et cumque consectetur porro exercitationem asperiores hic. Neque sapiente quod odit reiciendis commodi quo, ex impedit aperiam molestiae, eaque, dolores libero. Mollitia dolores dolore eum itaque dignissimos pariatur rerum incidunt, fuga saepe, doloribus, harum fugiat fugit suscipit iusto quo? Provident aliquam assumenda expedita unde amet neque? Neque harum, laborum doloremque sapiente ipsam facere adipisci.</p>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt fugit beatae sapiente perspiciatis repudiandae minus corrupti non dolores, harum illo, eligendi voluptatibus provident id saepe consectetur nisi facilis, numquam labore asperiores incidunt tempora architecto maiores reprehenderit necessitatibus! Dolores reprehenderit inventore saepe iure velit? Blanditiis praesentium dolorum, et cumque consectetur porro exercitationem asperiores hic. Neque sapiente quod odit reiciendis commodi quo, ex impedit aperiam molestiae, eaque, dolores libero. Mollitia dolores dolore eum itaque dignissimos pariatur rerum incidunt, fuga saepe, doloribus, harum fugiat fugit suscipit iusto quo? Provident aliquam assumenda expedita unde amet neque? Neque harum, laborum doloremque sapiente ipsam facere adipisci.</p>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt fugit beatae sapiente perspiciatis repudiandae minus corrupti non dolores, harum illo, eligendi voluptatibus provident id saepe consectetur nisi facilis, numquam labore asperiores incidunt tempora architecto maiores reprehenderit necessitatibus! Dolores reprehenderit inventore saepe iure velit? Blanditiis praesentium dolorum, et cumque consectetur porro exercitationem asperiores hic. Neque sapiente quod odit reiciendis commodi quo, ex impedit aperiam molestiae, eaque, dolores libero. Mollitia dolores dolore eum itaque dignissimos pariatur rerum incidunt, fuga saepe, doloribus, harum fugiat fugit suscipit iusto quo? Provident aliquam assumenda expedita unde amet neque? Neque harum, laborum doloremque sapiente ipsam facere adipisci.</p>              <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt fugit beatae sapiente perspiciatis repudiandae minus corrupti non dolores, harum illo, eligendi voluptatibus provident id saepe consectetur nisi facilis, numquam labore asperiores incidunt tempora architecto maiores reprehenderit necessitatibus! Dolores reprehenderit inventore saepe iure velit? Blanditiis praesentium dolorum, et cumque consectetur porro exercitationem asperiores hic. Neque sapiente quod odit reiciendis commodi quo, ex impedit aperiam molestiae, eaque, dolores libero. Mollitia dolores dolore eum itaque dignissimos pariatur rerum incidunt, fuga saepe, doloribus, harum fugiat fugit suscipit iusto quo? Provident aliquam assumenda expedita unde amet neque? Neque harum, laborum doloremque sapiente ipsam facere adipisci.</p>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt fugit beatae sapiente perspiciatis repudiandae minus corrupti non dolores, harum illo, eligendi voluptatibus provident id saepe consectetur nisi facilis, numquam labore asperiores incidunt tempora architecto maiores reprehenderit necessitatibus! Dolores reprehenderit inventore saepe iure velit? Blanditiis praesentium dolorum, et cumque consectetur porro exercitationem asperiores hic. Neque sapiente quod odit reiciendis commodi quo, ex impedit aperiam molestiae, eaque, dolores libero. Mollitia dolores dolore eum itaque dignissimos pariatur rerum incidunt, fuga saepe, doloribus, harum fugiat fugit suscipit iusto quo? Provident aliquam assumenda expedita unde amet neque? Neque harum, laborum doloremque sapiente ipsam facere adipisci.</p>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt fugit beatae sapiente perspiciatis repudiandae minus corrupti non dolores, harum illo, eligendi voluptatibus provident id saepe consectetur nisi facilis, numquam labore asperiores incidunt tempora architecto maiores reprehenderit necessitatibus! Dolores reprehenderit inventore saepe iure velit? Blanditiis praesentium dolorum, et cumque consectetur porro exercitationem asperiores hic. Neque sapiente quod odit reiciendis commodi quo, ex impedit aperiam molestiae, eaque, dolores libero. Mollitia dolores dolore eum itaque dignissimos pariatur rerum incidunt, fuga saepe, doloribus, harum fugiat fugit suscipit iusto quo? Provident aliquam assumenda expedita unde amet neque? Neque harum, laborum doloremque sapiente ipsam facere adipisci.</p>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt fugit beatae sapiente perspiciatis repudiandae minus corrupti non dolores, harum illo, eligendi voluptatibus provident id saepe consectetur nisi facilis, numquam labore asperiores incidunt tempora architecto maiores reprehenderit necessitatibus! Dolores reprehenderit inventore saepe iure velit? Blanditiis praesentium dolorum, et cumque consectetur porro exercitationem asperiores hic. Neque sapiente quod odit reiciendis commodi quo, ex impedit aperiam molestiae, eaque, dolores libero. Mollitia dolores dolore eum itaque dignissimos pariatur rerum incidunt, fuga saepe, doloribus, harum fugiat fugit suscipit iusto quo? Provident aliquam assumenda expedita unde amet neque? Neque harum, laborum doloremque sapiente ipsam facere adipisci.</p>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt fugit beatae sapiente perspiciatis repudiandae minus corrupti non dolores, harum illo, eligendi voluptatibus provident id saepe consectetur nisi facilis, numquam labore asperiores incidunt tempora architecto maiores reprehenderit necessitatibus! Dolores reprehenderit inventore saepe iure velit? Blanditiis praesentium dolorum, et cumque consectetur porro exercitationem asperiores hic. Neque sapiente quod odit reiciendis commodi quo, ex impedit aperiam molestiae, eaque, dolores libero. Mollitia dolores dolore eum itaque dignissimos pariatur rerum incidunt, fuga saepe, doloribus, harum fugiat fugit suscipit iusto quo? Provident aliquam assumenda expedita unde amet neque? Neque harum, laborum doloremque sapiente ipsam facere adipisci.</p>
                <p id='about' className=' text-bg-info'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt fugit beatae sapiente perspiciatis repudiandae minus corrupti non dolores, harum illo, eligendi voluptatibus provident id saepe consectetur nisi facilis, numquam labore asperiores incidunt tempora architecto maiores reprehenderit necessitatibus! Dolores reprehenderit inventore saepe iure velit? Blanditiis praesentium dolorum, et cumque consectetur porro exercitationem asperiores hic. Neque sapiente quod odit reiciendis commodi quo, ex impedit aperiam molestiae, eaque, dolores libero. Mollitia dolores dolore eum itaque dignissimos pariatur rerum incidunt, fuga saepe, doloribus, harum fugiat fugit suscipit iusto quo? Provident aliquam assumenda expedita unde amet neque? Neque harum, laborum doloremque sapiente ipsam facere adipisci.</p>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt fugit beatae sapiente perspiciatis repudiandae minus corrupti non dolores, harum illo, eligendi voluptatibus provident id saepe consectetur nisi facilis, numquam labore asperiores incidunt tempora architecto maiores reprehenderit necessitatibus! Dolores reprehenderit inventore saepe iure velit? Blanditiis praesentium dolorum, et cumque consectetur porro exercitationem asperiores hic. Neque sapiente quod odit reiciendis commodi quo, ex impedit aperiam molestiae, eaque, dolores libero. Mollitia dolores dolore eum itaque dignissimos pariatur rerum incidunt, fuga saepe, doloribus, harum fugiat fugit suscipit iusto quo? Provident aliquam assumenda expedita unde amet neque? Neque harum, laborum doloremque sapiente ipsam facere adipisci.</p>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt fugit beatae sapiente perspiciatis repudiandae minus corrupti non dolores, harum illo, eligendi voluptatibus provident id saepe consectetur nisi facilis, numquam labore asperiores incidunt tempora architecto maiores reprehenderit necessitatibus! Dolores reprehenderit inventore saepe iure velit? Blanditiis praesentium dolorum, et cumque consectetur porro exercitationem asperiores hic. Neque sapiente quod odit reiciendis commodi quo, ex impedit aperiam molestiae, eaque, dolores libero. Mollitia dolores dolore eum itaque dignissimos pariatur rerum incidunt, fuga saepe, doloribus, harum fugiat fugit suscipit iusto quo? Provident aliquam assumenda expedita unde amet neque? Neque harum, laborum doloremque sapiente ipsam facere adipisci.</p>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt fugit beatae sapiente perspiciatis repudiandae minus corrupti non dolores, harum illo, eligendi voluptatibus provident id saepe consectetur nisi facilis, numquam labore asperiores incidunt tempora architecto maiores reprehenderit necessitatibus! Dolores reprehenderit inventore saepe iure velit? Blanditiis praesentium dolorum, et cumque consectetur porro exercitationem asperiores hic. Neque sapiente quod odit reiciendis commodi quo, ex impedit aperiam molestiae, eaque, dolores libero. Mollitia dolores dolore eum itaque dignissimos pariatur rerum incidunt, fuga saepe, doloribus, harum fugiat fugit suscipit iusto quo? Provident aliquam assumenda expedita unde amet neque? Neque harum, laborum doloremque sapiente ipsam facere adipisci.</p>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt fugit beatae sapiente perspiciatis repudiandae minus corrupti non dolores, harum illo, eligendi voluptatibus provident id saepe consectetur nisi facilis, numquam labore asperiores incidunt tempora architecto maiores reprehenderit necessitatibus! Dolores reprehenderit inventore saepe iure velit? Blanditiis praesentium dolorum, et cumque consectetur porro exercitationem asperiores hic. Neque sapiente quod odit reiciendis commodi quo, ex impedit aperiam molestiae, eaque, dolores libero. Mollitia dolores dolore eum itaque dignissimos pariatur rerum incidunt, fuga saepe, doloribus, harum fugiat fugit suscipit iusto quo? Provident aliquam assumenda expedita unde amet neque? Neque harum, laborum doloremque sapiente ipsam facere adipisci.</p>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt fugit beatae sapiente perspiciatis repudiandae minus corrupti non dolores, harum illo, eligendi voluptatibus provident id saepe consectetur nisi facilis, numquam labore asperiores incidunt tempora architecto maiores reprehenderit necessitatibus! Dolores reprehenderit inventore saepe iure velit? Blanditiis praesentium dolorum, et cumque consectetur porro exercitationem asperiores hic. Neque sapiente quod odit reiciendis commodi quo, ex impedit aperiam molestiae, eaque, dolores libero. Mollitia dolores dolore eum itaque dignissimos pariatur rerum incidunt, fuga saepe, doloribus, harum fugiat fugit suscipit iusto quo? Provident aliquam assumenda expedita unde amet neque? Neque harum, laborum doloremque sapiente ipsam facere adipisci.</p>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt fugit beatae sapiente perspiciatis repudiandae minus corrupti non dolores, harum illo, eligendi voluptatibus provident id saepe consectetur nisi facilis, numquam labore asperiores incidunt tempora architecto maiores reprehenderit necessitatibus! Dolores reprehenderit inventore saepe iure velit? Blanditiis praesentium dolorum, et cumque consectetur porro exercitationem asperiores hic. Neque sapiente quod odit reiciendis commodi quo, ex impedit aperiam molestiae, eaque, dolores libero. Mollitia dolores dolore eum itaque dignissimos pariatur rerum incidunt, fuga saepe, doloribus, harum fugiat fugit suscipit iusto quo? Provident aliquam assumenda expedita unde amet neque? Neque harum, laborum doloremque sapiente ipsam facere adipisci.</p>
            </Container>
        </div>
    )
};
export default Forpractice;
